{{- range .Values.applications }}
{{- if .configmap }}
---
apiVersion: v1
data:
  {{- toYaml .configmap.data | nindent 2 }}
kind: ConfigMap
metadata:
  name: {{ include "exam.fullname" $ }}-{{ .name }}-configmap
{{- end }}
{{- end }}
