{{- range .Values.applications }}
---
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-deployment
  labels:
    app: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-deployment
  template:
    metadata:
      labels:
        app: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-deployment
    spec:
      {{- with .initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-container
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- if .command }}
          command: [ 'sh', '-c', {{ .command }}]
          {{- end }}
          {{- with .envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .containerPort }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}