{{- range .Values.applications }}
{{- if .persistentVolume }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-pv
  labels:
    app: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-pv
spec:
  storageClassName: {{ .persistentVolume.storageClassName }}
  capacity:
    storage: {{ .persistentVolume.capacity }}
  accessModes:
    {{- toYaml .persistentVolume.accessModes | nindent 4 }}
  hostPath:
    path: {{ .persistentVolume.hostPath }}
{{- end }}
{{- end }}