{{- range .Values.applications }}
{{- if .persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-pvc
  labels:
    app: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-pvc
spec:
  storageClassName: {{ .persistentVolumeClaim.storageClassName }}
  accessModes:
    {{- toYaml .persistentVolumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .persistentVolumeClaim.capacity }}
{{- end }}
{{- end }}