{{- range .Values.applications }}
{{- if .secret }}
---
apiVersion: v1
data:
  {{- toYaml .secret.data | nindent 2 }}
kind: Secret
metadata:
  name: {{ include "fastapiapp.fullname" $ }}-{{ .name }}-secret
type: {{ .secret.type }}
{{- end }}
{{- end }}
