{{- range $application := .Values.applications }}
{{- if .services }}
---
{{- range .services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" $ }}-{{ $application.name }}-service
  labels:
    app: {{ include "fastapiapp.fullname" $ }}-{{ $application.name }}-service
spec:
  {{- if .allocateLoadBalancerNodePorts }}
  allocateLoadBalancerNodePorts: {{ .allocateLoadBalancerNodePorts }}
  {{- end }}
  {{- if .type }}
  type: {{ .type }}
  {{- else }}
  type: {{ $.Values.service.type }}
  {{- end }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    app: {{ include "fastapiapp.fullname" $ }}-{{ $application.name }}-deployment
  {{- end }}
  {{- end }}
  {{- end }}